contact_admin:
  name: Admin
  email: admin@example.com

data:
  production_solaire_api: http://example.com/solar
  battery_api: http://example.com/battery

interface_config_dir: config/interfaces

db_path: data/wakeonstorage.sqlite

# Refresh interval (seconds) for AJAX calls (seconds)
ajax:
  refresh: 10          # general polling interval
  router_refresh: 10   # router status refresh interval
