contact_admin:
  name: Admin
  email: admin@example.com

data:
  production_solaire_api: http://example.com/solar
  battery_api: http://example.com/battery

interface_config_dir: config/interfaces

db_path: data/wakeonstorage.sqlite
