contact_admin:
  name: Admin
  email: admin@example.com

data:
  batterie:
    - url: https://wakeonstorage-local.retzo.net:8123/api/states/sensor.batterie_soc
      token: mysecrettoken
      ttl: 600        # cache lifetime in seconds
      type: home_assistant
  production_solaire:
    url: https://wakeonstorage-local.retzo.net:8123/api/states/sensor.prod_solaire
    token: mysecrettoken
    ttl: 600
    type: home_assistant
  production_solaire_estimation:
    url: https://api.solcast.com.au/rooftop_sites/xxx-xxx-xxx-xxx/forecasts?format=json
    token: mysecrettoken
    ttl: 10800
    type: solcast

interface_config_dir: config/interfaces

db_path: data/wakeonstorage.sqlite

# Enable verbose API logging in responses
debug: true

# Refresh interval (seconds) for AJAX calls (seconds)
ajax:
  refresh: 10          # general polling interval
  router_refresh: 10   # router status refresh interval
  batterie_refresh: 60
  production_solaire_refresh: 60
  production_solaire_estimation_refresh: 60
  storage_refresh: 10
